In [1]:
import pandas as pd

In [2]:
# 데이터 불러오기 

df_topic_news = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/실무인증/Data/df_topic_news_20220528.csv')
df_finance_data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/실무인증/Data/df_new_20220528.csv')
# df_fng = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/실무인증/Data/df_fng_20220528.csv')
# df_stock = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/실무인증/Data/df_stock_20220528.csv')
# df_trend = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/실무인증/Data/df_trend_20220528.csv')
df_eth = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/실무인증/Data/eth_df_20220528.csv')

In [3]:
df_topic_news = df_topic_news[['date','Dominant_Topic','Topic_Perc_Contrib']]
df_eth = df_eth.rename(columns={'date_kst':'date'})
df_eth = df_eth.drop(['market','candle_date_time_utc','candle_date_time_kst','date_utc'], axis=1)

In [4]:
df_finance_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1885 entries, 0 to 1884
Data columns (total 56 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  1885 non-null   object
 1   휘발유                   1885 non-null   float64
 2   고급휘발유                 1885 non-null   float64
 3   경유                    1885 non-null   float64
 4   두바이유                  1301 non-null   float64
 5   브렌트유                  1327 non-null   float64
 6   WTI(서부텍사스유)           1300 non-null   float64
 7   국내 금                  1271 non-null   float64
 8   국제 금                  1299 non-null   float64
 9   백금                    1299 non-null   float64
 10  은                     1299 non-null   float64
 11  팔라듐                   1299 non-null   float64
 12  가스오일                  1326 non-null   float64
 13  난방유                   1303 non-null   float64
 14  천연가스                  1302 non-null   float64
 15  구리                    1295 non-null   float64
 16  납                     1293 non-null   float64
 17  아연                    1293 non-null   float64
 18  니켈                    1293 non-null   float64
 19  알루미늄합금                1293 non-null   float64
 20  주석                    1293 non-null   float64
 21  옥수수                   1298 non-null   float64
 22  설탕                    1300 non-null   float64
 23  대두                    1298 non-null   float64
 24  대두박                   1298 non-null   float64
 25  대두유                   1298 non-null   float64
 26  면화                    1300 non-null   float64
 27  소맥                    1298 non-null   float64
 28  쌀                     1298 non-null   float64
 29  오렌지주스                 1300 non-null   float64
 30  커피                    1300 non-null   float64
 31  코코아                   1300 non-null   float64
 32  달러/대한민국 원             1271 non-null   float64
 33  영국 파운드/달러             1612 non-null   float64
 34  유로/달러                 1612 non-null   float64
 35  달러/일본 엔               1611 non-null   float64
 36  달러/캐나다 달러             1611 non-null   float64
 37  달러/스위스 프랑             1611 non-null   float64
 38  달러/중국 위안              1610 non-null   float64
 39  달러/스웨덴 크로나            1610 non-null   float64
 40  CD금리(91일)             1264 non-null   float64
 41  콜금리(1일)               1269 non-null   float64
 42  국고채(3년)               1264 non-null   float64
 43  회사채(3년)               1264 non-null   float64
 44  COFIX잔액               1298 non-null   float64
 45  COFIX신규취급액            1298 non-null   float64
 46  samsung_trade_price   1246 non-null   float64
 47  samsung_trade_volume  1246 non-null   float64
 48  hynix_trade_price     1246 non-null   float64
 49  hynix_trade_volume    1246 non-null   float64
 50  nvdia_trade_price     1280 non-null   float64
 51  nvdia_trade_volume    1280 non-null   float64
 52  amd_trade_price       1280 non-null   float64
 53  amd_trade_volume      1280 non-null   float64
 54  fng                   1576 non-null   float64
 55  이더리움_구글트랜드            260 non-null    float64
dtypes: float64(55), object(1)
memory usage: 824.8+ KB

In [5]:
df_topic_news.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1602 entries, 0 to 1601
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                1602 non-null   object
 1   Dominant_Topic      1602 non-null   int64
 2   Topic_Perc_Contrib  1602 non-null   float64
dtypes: float64(1), int64(1), object(1)
memory usage: 37.7+ KB

In [6]:
df_eth.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1705 entries, 0 to 1704
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   opening_price            1705 non-null   float64
 1   high_price               1705 non-null   float64
 2   low_price                1705 non-null   float64
 3   trade_price              1705 non-null   float64
 4   timestamp                1705 non-null   int64
 5   candle_acc_trade_price   1705 non-null   float64
 6   candle_acc_trade_volume  1705 non-null   float64
 7   prev_closing_price       1704 non-null   float64
 8   change_price             1699 non-null   float64
 9   change_rate              1705 non-null   float64
 10  MA5                      1669 non-null   float64
 11  MA20                     1534 non-null   float64
 12  MA60                     1174 non-null   float64
 13  date                     1705 non-null   object
dtypes: float64(12), int64(1), object(1)
memory usage: 186.6+ KB

In [7]:
df_1 = pd.merge(df_finance_data, df_topic_news,  how='outer', on='date')
df_train_data = pd.merge(df_1, df_eth,  how='outer', on='date')

# eth의 데이터가 '2017-09-25' 이후 존재
df_train_data = df_train_data.loc[df_train_data['date'] > '2017-09-24']
print(df_train_data['date'].min())

2017-09-25

In [8]:
# df_train_data['date'] = pd.to_datetime(df_train_data['date'], format='%Y-%m-%d')

In [9]:
df_train_data = df_train_data.sort_values(by='date', ascending=False)
df_train_data = df_train_data.fillna(method='bfill')
df_train_data = df_train_data.fillna(method='ffill')
df_train_data

,date,휘발유,고급휘발유,경유,두바이유,브렌트유,WTI(서부텍사스유),국내 금,국제 금,백금,...,trade_price,timestamp,candle_acc_trade_price,candle_acc_trade_volume,prev_closing_price,change_price,change_rate,MA5,MA20,MA60
0,2022-05-29,2008.84,2226.22,2006.10,110.86,115.56,115.07,74845.11,1851.3,945.5,...,2296000.0,1.653836e+12,4.324261e+10,18916.963461,2286000.0,10000.0,0.004374,2323000.0,2583000.0,3.390133e+06
1,2022-05-28,2007.85,2225.83,2005.71,110.86,115.56,115.07,74845.11,1851.3,945.5,...,2286000.0,1.653782e+12,8.143222e+10,36021.515318,2225000.0,61000.0,0.027416,2368800.0,2620100.0,3.419633e+06
2,2022-05-27,2004.87,2223.46,2005.13,110.86,115.56,115.07,74845.11,1851.3,945.5,...,2225000.0,1.653696e+12,1.790979e+11,79286.264660,2314000.0,-89000.0,-0.038462,2418200.0,2671350.0,3.449633e+06
3,2022-05-26,2001.82,2219.47,2003.86,109.78,114.17,114.09,75176.73,1847.6,939.9,...,2314000.0,1.653610e+12,2.262575e+11,95110.336050,2494000.0,-180000.0,-0.072173,2498600.0,2732900.0,3.479633e+06
4,2022-05-25,1998.96,2217.03,2002.77,106.92,111.12,110.33,75479.26,1846.3,931.8,...,2494000.0,1.653523e+12,8.411180e+10,33407.422726,2525000.0,-31000.0,-0.012277,2546200.0,2793000.0,3.506583e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1703,2017-09-29,1495.46,1829.81,1286.30,53.66,57.54,51.67,47447.33,1281.5,910.3,...,327500.0,1.506729e+12,1.704665e+04,0.052300,332500.0,-5000.0,-0.015038,329800.0,344900.0,3.642692e+05
1704,2017-09-28,1493.88,1826.03,1284.76,53.63,57.41,51.56,47361.67,1285.5,921.0,...,332500.0,1.506643e+12,1.670575e+04,0.049700,342500.0,-10000.0,-0.029197,329800.0,344900.0,3.642692e+05
1705,2017-09-27,1492.61,1828.77,1283.51,53.66,57.90,52.14,47418.46,1283.4,921.3,...,342500.0,1.506557e+12,1.667225e+04,0.050700,321500.0,21000.0,0.065319,329800.0,344900.0,3.642692e+05
1706,2017-09-26,1491.59,1827.40,1282.56,53.76,58.44,51.88,47769.37,1297.0,924.5,...,321500.0,1.506470e+12,1.674780e+04,0.051600,325000.0,-3500.0,-0.010769,329800.0,344900.0,3.642692e+05
1707,2017-09-25,1490.52,1829.13,1281.54,53.92,59.02,52.22,47064.48,1306.8,940.0,...,325000.0,1.506384e+12,4.590101e+08,1421.855427,325000.0,-3500.0,0.000000,329800.0,344900.0,3.642692e+05

In [24]:
import pickle

with open('/content/drive/MyDrive/Colab Notebooks/실무인증/Data/crypto_currency_data_v1.pickle', 'wb') as f:
    pickle.dump(df_train_data, f)

In [25]:
with open('/content/drive/MyDrive/Colab Notebooks/실무인증/Data/crypto_currency_data_v1.pickle', 'rb') as f:
    data = pickle.load(f)

In [27]:
data

,date,휘발유,고급휘발유,경유,두바이유,브렌트유,WTI(서부텍사스유),국내 금,국제 금,백금,...,trade_price,timestamp,candle_acc_trade_price,candle_acc_trade_volume,prev_closing_price,change_price,change_rate,MA5,MA20,MA60
0,2022-05-29,2008.84,2226.22,2006.10,110.86,115.56,115.07,74845.11,1851.3,945.5,...,2296000.0,1.653836e+12,4.324261e+10,18916.963461,2286000.0,10000.0,0.004374,2323000.0,2583000.0,3.390133e+06
1,2022-05-28,2007.85,2225.83,2005.71,110.86,115.56,115.07,74845.11,1851.3,945.5,...,2286000.0,1.653782e+12,8.143222e+10,36021.515318,2225000.0,61000.0,0.027416,2368800.0,2620100.0,3.419633e+06
2,2022-05-27,2004.87,2223.46,2005.13,110.86,115.56,115.07,74845.11,1851.3,945.5,...,2225000.0,1.653696e+12,1.790979e+11,79286.264660,2314000.0,-89000.0,-0.038462,2418200.0,2671350.0,3.449633e+06
3,2022-05-26,2001.82,2219.47,2003.86,109.78,114.17,114.09,75176.73,1847.6,939.9,...,2314000.0,1.653610e+12,2.262575e+11,95110.336050,2494000.0,-180000.0,-0.072173,2498600.0,2732900.0,3.479633e+06
4,2022-05-25,1998.96,2217.03,2002.77,106.92,111.12,110.33,75479.26,1846.3,931.8,...,2494000.0,1.653523e+12,8.411180e+10,33407.422726,2525000.0,-31000.0,-0.012277,2546200.0,2793000.0,3.506583e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1703,2017-09-29,1495.46,1829.81,1286.30,53.66,57.54,51.67,47447.33,1281.5,910.3,...,327500.0,1.506729e+12,1.704665e+04,0.052300,332500.0,-5000.0,-0.015038,329800.0,344900.0,3.642692e+05
1704,2017-09-28,1493.88,1826.03,1284.76,53.63,57.41,51.56,47361.67,1285.5,921.0,...,332500.0,1.506643e+12,1.670575e+04,0.049700,342500.0,-10000.0,-0.029197,329800.0,344900.0,3.642692e+05
1705,2017-09-27,1492.61,1828.77,1283.51,53.66,57.90,52.14,47418.46,1283.4,921.3,...,342500.0,1.506557e+12,1.667225e+04,0.050700,321500.0,21000.0,0.065319,329800.0,344900.0,3.642692e+05
1706,2017-09-26,1491.59,1827.40,1282.56,53.76,58.44,51.88,47769.37,1297.0,924.5,...,321500.0,1.506470e+12,1.674780e+04,0.051600,325000.0,-3500.0,-0.010769,329800.0,344900.0,3.642692e+05
1707,2017-09-25,1490.52,1829.13,1281.54,53.92,59.02,52.22,47064.48,1306.8,940.0,...,325000.0,1.506384e+12,4.590101e+08,1421.855427,325000.0,-3500.0,0.000000,329800.0,344900.0,3.642692e+05